var lang = {
  'en_us': {
    'title-text': 'Midori and Andrew',
    'Home-Btn': 'Home',
    'Schedule-Btn': 'Schedule',
    'Lodging-Btn': 'Lodging',
    'FAQ-Btn': 'FAQ',
    'RSVP-Btn': 'RSVP',
    'US-Title': '<b>Us</b>',
    'US-Text': "<p><i>Our first date took place on a cold and snowy January night at an outdoor skating rink in Ann Arbor.  Midori quickly grabbed Andrew's hand after stepping onto the ice, and we haven't let go since. <br><br>That first hygge winter of exploring bookstores and cooking together led to springtime runs, summer hikes, and autumn cider mill dates, all interspersed with trips to Tampa and Detroit to visit family.  After working and studying in separate cities (Seattle, Philadelphia, Ann Arbor, and Atlanta) for over a year, we’re especially happy to be in the same city at last.  We’ve enjoyed celebrating many milestones while dating, Andrew’s Master's graduation from Michigan, Midori passing her PhD quals at Georgia Tech, and our Confirmation in the Catholic Church together, but we’re especially happy to be engaged and can’t wait to celebrate our marriage with you soon!</i></p>",
    'Destination-Title': "<b>Destination</b>",
    'Destination-Text': "<p><i>Known as the “Sunshine City” with 361 days of clear skies per year, St. Petersburg is home to beautiful, award-winning beaches, the world-renowned Salvador Dali Museum, top-rated restaurants and beautiful Fort De Soto Park.  It's where we got engaged and we’re excited to spend a weekend with you in a city that holds a special place in our hearts.</i></p>",
    'Wedding-Title': "<b>The Wedding</b>",
    'Wedding-Text': "<p>Parking is available at both St. Mary's and the Poynter Institute.  The locations are also within walking distance (just two blocks) of each other</p>",
    'Ceremony-Text': "Ceremony",
    'Wedding-Mass-Text': "<p>Wedding Mass - 12:45pm</p>",
    'Reception-Text': "Reception",
    'Cocktail-Text': "<p>Cocktail Hour - 3:30pm</p>",
    'Dinner-Text': "<p>Dinner and Dancing - 4:30pm</p>",
    'Afterparty-Text': "Afterparty",
    'TBA-Text': "TBA",
    'Unofficial-Afterparty-Text': "<p>Unofficial afterparty - 9:00pm</p>",
    'Activities-Title': "<b>Local Area Activities</b>",
    'Activities-Text': "<p>Below are links to a few of our favorite spots and other local suggestions that we’d be excited for you to check out. You can also follow our <a href='https://goo.gl/maps/3hDYTYFquWyzdSjg7' target='_blank'><u>google list</u></a> for a more complete list of our recommendations.</p>",
    'Activities-Coffee': "Coffee",
    'Activities-Lunch': "Lunch/Dinner",
    'Activities-Drinks': "Drinks",
    'Activities-Parks': "Parks/Museums",
    'Activities-Beaches': "Beaches",
    'Lodging-Title': "<b>Lodging</b>",
    'Lodging-Hyatt': "<p style='margin-left:10px;margin-right:10px'>We’ve reserved rooms at the Hyatt in downtown St. Pete.  It's walking distance to the restaurants and shops along Beach Dr. and only a half mile north of St. Mary's</p>",
    'Lodging-Airbnb': "<p style='margin-left:10px;margin-right:10px'>There are plenty of options available if you'd like to explore the St. Pete area from a local's perspective by renting a cozy beach bungalow, house, or apartment downtown. This is a great option for large groups traveling together.</p>",
    'Lodging-Reserve': "Reserve a Room",
    'Bridal-Party': "<b>Bridal Party</b>",
    'Registry-Title': "<b>Registry</b>",
    'Registry-Text': "<p><i>What we want most of all for our wedding is to have all of our family and friends there to celebrate with us, and so, more than anything, we would simply enjoy your presence. (We mean it!) But, if you really feel compelled to get us something, a few items we could use in making our home together can be found here</i></p>",
    'Registry-Amazon': "Registry on Amazon",
    'Registry-Pottery-Barn': "Registry on Pottery Barn",
    'See-You': "<b>We hope to see you there!</b>",
    'FAQ-Title': "<b>FAQ</b>",
    'FAQ-Text': "<p><i>If you have any other questions not answered here, please email us at <a href = 'mailto: andrewandmidori28@gmail.com'>andrewandmidori28@gmail.com</a></i></p>",
    'FAQ-Travel': "Travel",
    'FAQ-Attire-Title': "What to wear",
    'FAQ-Attire-Text': "Formal attire, black tie optional",
    'FAQ-Weather-Title': "Weather",
    'FAQ-Weather-Text': "Typical temperatures in Janurary for St. Pete  range from the upper 60s to low 70s",
    'FAQ-Transportation-Title': "Transportation",
    'FAQ-Transportation-Text': "Uber/Lyft from Tampa International Airport to downtown St. Pete typically runs around $40.  Most local attractions are centrally located and we recommend using a ridesharing service or walking to save the hassle of parking downtown.",
    'FAQ-Ceremony': "Ceremony/Reception",
    'FAQ-Parking-Title': "Parking",
    'FAQ-Parking-Text': "St Mary's has a small parking lot with spaces available on a first come first serve basis.  Vehicles must be moved after ther ceremony to accomodate parishoners attending the afternoon and evening masses.  Gated parking is available at the Poynter Institute",
    'FAQ-Food-Title': "Food",
    'FAQ-Food-Text': "Entrees will be guest choice tableside.  Please communicate any dietary restrictions to the wait staff when they take your selection",
    'FAQ-Alcohol-Title': "Alcohol",
    'FAQ-Alcohol-Text': "Open bar to all guests of legal drinking age",
    'FAQ-Photos-Title': "Photos",
    'FAQ-Photo-Policy': "Policy",
    'FAQ-Photos-Text': "<p>Please make sure to turn off all your phones and cameras during the ceremony. A professional photographer will be capturing this special moment and we promise to share all of the pictures with our guests!</p>",
    'Respond': "<b>Kindly Respond By December, 2020</b>",
    'covid': "During this uncertain time with COVID-19, we are monitoring the situation closely and will communicate any changes due to local regulations or public health guidance. We are prepared to take every precaution necessary to make our wedding safe for our guests. Our wedding is currently happening as planned, and we look forward to celebrating with you all on Janurary 16, 2021"
  },
  'es_mx': {
    'title-text': 'Midori y Andrew',
    'Home-Btn': 'Inicio',
    'Schedule-Btn': 'Programa',
    'Lodging-Btn': 'Hospedaje',
    'FAQ-Btn': 'Preguntas Frecuentes',
    'RSVP-Btn': 'RSVP',
    'US-Title': '<b>Nuestra Historia</b>',
    'US-Text': "<p><i>Nuestra primera cita fue patinando sobre el hielo en una noche fría y nevada de Enero en Ann Arbor, Michigan. Al pisar en el hielo, Midori extendió su mano a Andrew, él la tomó de la mano y no la ha dejado ir desde ese día.<br><br>Los días invernales en los que disfrutamos cocinar juntos y explorar librerías se convirtieron en salidas a correr en la primavera, caminatas en el verano y citas en las sidrerías de manzanas en el otoño. Mientras tanto, siempre viajábamos a Tampa y Detroit para visitar a nuestras familias. Después de trabajar y estudiar en ciudades diferentes (Seattle, Philadelphia, Ann Arbor, y Atlanta) por mas de un año, estamos muy alegres que al fin estamos en la misma ciudad. Hemos celebrado muchos momentos significativos desde que empezamos a salir incluyendo la graduación de Maestría de Andrew en Michigan, Midori pasando su primera prueba de calificación de Doctorado en Georgia Tech, y nuestra Confirmación en la Iglesia Católica juntos. ¡Ahora estamos especialmente emocionados de estar comprometidos y por celebrar nuestro matrimonio contigo pronto!</i></p>",
    'Destination-Title': "<b>Lugar</b>",
    'Destination-Text': "<p><i>Conocida como la “Ciudad Soleada” con 361 días de cielos despejados cada año, St. Petersburg es el hogar de hermosas playas galardonadas, el Museo de Salvador Dalí, excelentes restaurantes y el hermoso parque Fort De Soto. St. Petersburg es donde nos comprometimos y estamos emocionados de pasar un fin de semana con nuestros seres queridos en una ciudad que ocupa un lugar especial en nuestros corazones.</i></p>",
    'Wedding-Title': "<b>La Boda</b>",
    'Wedding-Text': "<p>Hay estacionamiento disponible tanto en la Iglesia St. Mary’s, como en el Poynter Insitute, local de la recepción. Los dos lugares están a solo dos cuadras el uno del otro.</p>",
    'Ceremony-Text': "Ceremonia",
    'Wedding-Mass-Text': "<p>Misa de Matrimonio - 12:45pm</p>",
    'Reception-Text': "Recepción",
    'Cocktail-Text': "<p>Hora de cóctel - 3:30pm</p>",
    'Dinner-Text': "<p>Cena y Baile - 4:30pm</p>",
    'Afterparty-Text': "Afterparty",
    'TBA-Text': "Será anunciado más tarde",
    'Unofficial-Afterparty-Text': "<p>Tornaboda (No oficial) - 9:00pm</p>",
    'Activities-Title': "<b>Actividades Locales</b>",
    'Activities-Text': "A continuación hay enlaces a algunos de nuestros <a href='https://goo.gl/maps/3hDYTYFquWyzdSjg7' target='_blank'><u>lugares favoritos</u></a> y otras sugerencias locales que recomendamos a nuestros invitados.",
    'Activities-Coffee': "Café",
    'Activities-Lunch': "Cena",
    'Activities-Drinks': "Bebidas",
    'Activities-Parks': "Sitios",
    'Activities-Beaches': "Playas",
    'Lodging-Title': "<b>Hospedaje</b>",
    'Lodging-Hyatt': "<p style='margin-left:10px;margin-right:10px'>Hemos reservado un bloque de habitaciones en el hotel Hyatt Place St. Petersburg/Downtown. El hotel está a media milla de la ceremonia y a sólo dos cuadras de los restaurantes y las atracciones a lo largo de Beach Drive en Downtown.</p>",
    'Lodging-Airbnb': "<p style='margin-left:10px;margin-right:10px'>Hay muchas opciones disponibles si desea explorar el área de St. Pete desde la perspectiva de una persona local. A través de Airbnb, puede alquilar un acogedor “bungalow” en la playa, una casa, o un apartamento en el centro de St. Pete. Esta es una buena opción para grupos grandes que están viajando juntos.</p>",
    'Lodging-Reserve': "Reservar una habitación",
    'Bridal-Party': "<b>Corte de Bodas</b>",
    'Registry-Title': "<b>Registro</b>",
    'Registry-Text': "<p><i>Lo que más deseamos en nuestra boda es celebrar con nuestra familia y amistades, y por eso, más que nada, simplemente disfrutaremos tener su presencia. (¡Es en serio!) Pero, si realmente le gustaría obsequiarnos algo, aqui puede encontrar algunos artículos que nos ayudarán a empezar nuestro nuevo hogar juntos.</i></p>",
    'Registry-Amazon': "Registro en Amazon",
    'Registry-Pottery-Barn': "Registro en Pottery Barn",
    'See-You': "<b>¡Esperamos verte ahí!</b>",
    'FAQ-Title': "<b>Preguntas Frecuentes</b>",
    'FAQ-Text': "<p><i>Si tienen alguna otra pregunta no respondida aquí, porfavor envíenos un mensaje a nuestro correo electrónico: <a href = 'mailto: andrewandmidori28@gmail.com'>andrewandmidori28@gmail.com</a></i></p>",
    'FAQ-Travel': "Viaje",
    'FAQ-Attire-Title': "Vestimenta",
    'FAQ-Attire-Text': "Formal",
    'FAQ-Weather-Title': "Clima",
    'FAQ-Weather-Text': "Las temperaturas típicas en enero en St. Pete varían entre los 60 grados y los 70 grados Farenheit.",
    'FAQ-Transportation-Title': "Transportación",
    'FAQ-Transportation-Text': "Recomendamos las aplicaciones para pedir un viaje como Uber y Lyft para transportarse del aeropuerto Tampa International Airport al área de downtown St. Petersburg. Un viaje del aeropuerto hasta St. Pete cuesta, en promedio, $40 USD por un carro. La mayoría de las otras atracciones están cercanas y recomendamos usar Uber y Lyft, o caminar, para evitar la molestia de buscar estacionamiento en el centro.",
    'FAQ-Ceremony': "Ceremonia y Recepción",
    'FAQ-Parking-Title': "Estacionamiento",
    'FAQ-Parking-Text': "St. Mary’s tiene un pequeño estacionamiento con espacios disponibles por orden de llegada. Los vehículos deben ser transladados después de la ceremonia para acomodar a los feligreses que asisten a las misas de la tarde y la noche. El estacionamiento privado con varios espacios está disponible en el Instituto Poynter para la recepción.",
    'FAQ-Food-Title': "Cena",
    'FAQ-Food-Text': "Nuestros invitados podrán elegir sus preferencias para la cena al sentarse. Por favor comunique cualquier restricción dietética al personal de servicio cuando tomen su selección.",
    'FAQ-Alcohol-Title': "Bebidas",
    'FAQ-Alcohol-Text': "Barra libre para todos los invitados en edad legal para beber.",
    'FAQ-Photos-Title': "Fotos",
    'FAQ-Photo-Policy': "Póliza",
    'FAQ-Photos-Text': "<p>Por favor asegúrese de apagar su teléfono y cámara durante la misa. ¡Un fotógrafo professional capturará este momento especial y prometemos compartir todas la fotos con nuestros invitados!</p>",
    'Respond': "<b>Por favor, les agradecemos responder antes de diciembre de 2020</b>",
    'covid': "Durante este tiempo de incertidumbre debido a COVID-19, estamos monitoreando atentamente la situación y comunicaremos cualquier cambio según las regulaciones locales y las guías de salud pública. Estamos preparados para tomar todas las precauciones necesarias para que nuestra boda sea segura para nuestros invitados. ¡Actualmente, nuestra boda se llevará a cabo según lo planeado, y esperamos celebrar con ustedes el 16 de enero de 2021!"
  }
};